In [1]:
import nltk
import numpy as np
import pandas as pd


In [2]:
df=pd.read_csv('spam.csv')
df=df.sample(5574)
df.head()

sms  label
2128  Tessy..pls do me a favor. Pls convey my birthd...      0
4638  Oh ho. Is this the first time u use these type...      0
3017  &lt;#&gt;  is fast approaching. So, Wish u a v...      0
1764  Joy's father is John. Then John is the NAME of...      0
5478  Yes princess! I want to please you every night...      0

In [3]:
import re

In [4]:
def clean_html(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
df['sms']=df['sms'].apply(clean_html)
df

sms  label
2128  Tessy..pls do me a favor. Pls convey my birthd...      0
4638  Oh ho. Is this the first time u use these type...      0
3017  &lt;#&gt;  is fast approaching. So, Wish u a v...      0
1764  Joy's father is John. Then John is the NAME of...      0
5478  Yes princess! I want to please you every night...      0
...                                                 ...    ...
4390                        K I'm ready,  &lt;#&gt; ?\n      0
3541  I'll get there at 3, unless you guys want me t...      0
1177  Did he say how fantastic I am by any chance, o...      0
163   I'm so in love with you. I'm excited each day ...      0
799                   Ok i msg u b4 i leave my house.\n      0

[5574 rows x 2 columns]

In [5]:
# function to remove special characters

def remove_special(text):
    x=''
    
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x + ' '
    return x
df['sms']=df['sms'].apply(remove_special)
df.head()

sms  label
2128  Tessy  pls do me a favor  Pls convey my birthd...      0
4638  Oh ho  Is this the first time u use these type...      0
3017   lt   gt   is fast approaching  So  Wish u a v...      0
1764  Joy s father is John  Then John is the NAME of...      0
5478  Yes princess  I want to please you every night...      0

In [6]:
# converting everything to lower

def convert_lower(text):
    return text.lower()
df['sms']=df['sms'].apply(convert_lower)
df.head()

sms  label
2128  tessy  pls do me a favor  pls convey my birthd...      0
4638  oh ho  is this the first time u use these type...      0
3017   lt   gt   is fast approaching  so  wish u a v...      0
1764  joy s father is john  then john is the name of...      0
5478  yes princess  i want to please you every night...      0

In [7]:
# Remove the stop words
from nltk.corpus import stopwords
stopwords=list(stopwords.words('english'))
stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [8]:
def remove_stopwords(text):
    x=[]
    for i in text.split():
        
        if i not in stopwords:
            x.append(i)
    y=x[:]
    x.clear()
    return y
df['sms']=df['sms'].apply(remove_stopwords)
df.head()

sms  label
2128  [tessy, pls, favor, pls, convey, birthday, wis...      0
4638         [oh, ho, first, time, u, use, type, words]      0
3017  [lt, gt, fast, approaching, wish, u, happy, ne...      0
1764  [joy, father, john, john, name, joy, father, m...      0
5478  [yes, princess, want, please, every, night, wi...      0

In [9]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z
df['sms']=df['sms'].apply(stem_words)
df.head()

sms  label
2128  [tessi, pl, favor, pl, convey, birthday, wish,...      0
4638          [oh, ho, first, time, u, use, type, word]      0
3017  [lt, gt, fast, approach, wish, u, happi, new, ...      0
1764  [joy, father, john, john, name, joy, father, m...      0
5478  [ye, princess, want, pleas, everi, night, wish...      0

In [10]:
def join_back(list_input):
    return " ".join(list_input)
    
df['sms']=df['sms'].apply(join_back)
df.head()

sms  label
2128  tessi pl favor pl convey birthday wish nimya p...      0
4638                   oh ho first time u use type word      0
3017  lt gt fast approach wish u happi new year happ...      0
1764        joy father john john name joy father mandan      0
5478    ye princess want pleas everi night wish command      0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)
cv.fit(df['sms'])
X=cv.fit_transform(df['sms']).toarray()
X.shape
y=df['label']

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(X_train)
print(y_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
3150    0
176     0
4674    0
4837    0
1635    1
       ..
5180    1
292     0
1166    0
1253    0
3798    0
Name: label, Length: 4459, dtype: int64


In [13]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

BernoulliNB()

In [14]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

from sklearn.metrics import accuracy_score

print("Gaussian",accuracy_score(y_test,y_pred1))
print("Multinomial",accuracy_score(y_test,y_pred2))
print("Bernaulli",accuracy_score(y_test,y_pred3))

Gaussian 0.8573991031390135
Multinomial 0.9838565022421525
Bernaulli 0.9811659192825112


**Therefore, we choose Bernoulli as our final model**

**Forming the User Interface**

In [22]:
review=input("Enter the message: ")
review=clean_html(review)
review=remove_special(review)
review=convert_lower(review)
review=remove_stopwords(review)
y=[]
review=stem_words(review)
review=join_back(review)
review_new=[]
review_new.append(review)
review_new
review_new=cv.transform(review_new).toarray()
prediction=clf1.predict(review_new)
print(prediction[0])

if(prediction[0]==0):
    print("NOT SPAM!")
else:  
    print("SPAM!")

#Great Movie Really like it a lot

Enter the message:  Reply STOP to unsubscribe from our service.


1
SPAM!
